"""Route snapshot test to ensure all endpoints exist after refactoring.

This test verifies that all baseline endpoints from main.py are still
accessible after moving them to routers. It prevents accidental 404s.
"""

from fastapi import FastAPI
from fastapi.testclient import TestClient


# Baseline routes from main.py (before refactoring)
# Format: (method, path)
BASELINE_ROUTES = {
    ("GET", "/media/proxy"),
    ("GET", "/health"),
    ("GET", "/health/observability"),
    ("GET", "/health/memory"),
    ("GET", "/health/workers"),
    ("GET", "/health/preflight"),
    ("POST", "/api/v1/messages"),
    ("POST", "/api/v1/sitniks/update-status"),
    ("POST", "/webhooks/manychat"),
    ("POST", "/webhooks/manychat/followup"),
    # Removed: /webhooks/manychat/create-order (CRM orders disabled)
    # Removed: /webhooks/snitkix/* (CRM webhooks disabled)
    ("POST", "/automation/mirt-summarize-prod-v1"),
    ("POST", "/automation/mirt-followups-prod-v1"),
    # Telegram webhook path is dynamic (settings.TELEGRAM_WEBHOOK_PATH)
    # We'll check it separately if needed
}


def get_app_routes(app: FastAPI) -> set[tuple[str, str]]:
    """Extract all (method, path) tuples from FastAPI app."""
    routes = set()
    for route in app.routes:
        # FastAPI routes have methods and path
        if hasattr(route, "methods") and hasattr(route, "path"):
            for method in route.methods:
                if method != "HEAD":  # Skip HEAD (auto-generated by FastAPI)
                    routes.add((method, route.path))
    return routes


def test_all_baseline_routes_exist():
    """Verify all baseline routes still exist after refactoring."""
    from src.server.main import app

    client = TestClient(app)
    app_routes = get_app_routes(app)

    # Check that all baseline routes exist
    missing_routes = BASELINE_ROUTES - app_routes

    if missing_routes:
        # Format error message nicely
        missing_str = "\n".join(f"  {method} {path}" for method, path in sorted(missing_routes))
        raise AssertionError(
            f"Missing routes after refactoring:\n{missing_str}\n\n"
            f"Total baseline routes: {len(BASELINE_ROUTES)}\n"
            f"Total app routes: {len(app_routes)}\n"
            f"Missing: {len(missing_routes)}"
        )

    # Also check that we didn't accidentally add unexpected routes
    # (This is informational, not a failure)
    extra_routes = app_routes - BASELINE_ROUTES
    if extra_routes:
        # Filter out common FastAPI routes (docs, openapi.json, etc.)
        known_extras = {
            ("GET", "/docs"),
            ("GET", "/redoc"),
            ("GET", "/openapi.json"),
            ("GET", "/"),
        }
        unexpected = extra_routes - known_extras
        if unexpected:
            # Log but don't fail - new routes might be intentional
            print(f"Note: Found additional routes (not in baseline): {unexpected}")


def test_health_endpoint_accessible():
    """Smoke test: verify /health endpoint is accessible."""
    from src.server.main import app

    client = TestClient(app)
    response = client.get("/health")
    assert response.status_code in (200, 503), f"Expected 200 or 503, got {response.status_code}"
    data = response.json()
    assert "status" in data, "Health endpoint should return status field"


def test_media_proxy_endpoint_exists():
    """Smoke test: verify /media/proxy endpoint exists (may return 404 if disabled)."""
    from src.server.main import app

    client = TestClient(app)
    # Don't provide required params - should get 422 (validation error) not 404
    response = client.get("/media/proxy")
    # 422 = validation error (endpoint exists), 404 = endpoint not found
    assert response.status_code in (400, 404, 422), (
        f"Expected 400/404/422, got {response.status_code}. "
        "If 404, endpoint might be missing after refactoring."
    )

