"""Fail CI when newly added lines introduce AI-smell markers or merge conflicts."""

from __future__ import annotations

import re
import subprocess
import sys
from dataclasses import dataclass


BANNED_MARKERS = (
    "SENIOR-LEVEL",
    "ЗАЛІЗОБЕТОННО",
    "AI wrote this",
)

AI_DISCLOSURE_RE = re.compile(
    r"(as an ai|chatgpt|generated by ai|copilot|llm generated|written by ai)",
    re.IGNORECASE,
)

MERGE_CONFLICT_RE = re.compile(r"^(<<<<<<< .+|=======|>>>>>>> .+)$")

SOURCE_FILE_RE = re.compile(r"^\+\+\+ b/((?:src|tests|scripts)/.+\.pyi?)$")


@dataclass(frozen=True)
class Finding:
    path: str
    line_no: int
    reason: str
    snippet: str


def _git_added_lines() -> list[tuple[str, int, str]]:
    """Return (file, line_no, line_text) for added lines in HEAD commit."""
    result = subprocess.run(
        ["git", "show", "--unified=0", "--pretty=format:", "HEAD"],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return []

    findings: list[tuple[str, int, str]] = []
    current_file: str | None = None
    current_new_line = 0
    for raw in result.stdout.splitlines():
        file_match = SOURCE_FILE_RE.match(raw)
        if file_match:
            current_file = file_match.group(1)
            current_new_line = 0
            continue

        if raw.startswith("@@"):
            # Parse hunk header, e.g. @@ -10,0 +11,3 @@
            plus_part = raw.split("+", 1)[1].split(" ", 1)[0]
            current_new_line = int(plus_part.split(",")[0])
            continue

        if current_file is None:
            continue
        if raw.startswith("+++ ") or raw.startswith("--- "):
            continue
        if raw.startswith("+"):
            findings.append((current_file, current_new_line, raw[1:]))
            current_new_line += 1
        elif raw.startswith("-"):
            continue
        else:
            current_new_line += 1
    return findings


def _detect_findings(added_lines: list[tuple[str, int, str]]) -> list[Finding]:
    findings: list[Finding] = []
    for path, line_no, text in added_lines:
        snippet = text.strip()

        if MERGE_CONFLICT_RE.match(snippet):
            findings.append(
                Finding(path=path, line_no=line_no, reason="merge-conflict-marker", snippet=snippet)
            )

        if "#" in text:
            for marker in BANNED_MARKERS:
                if marker in text:
                    findings.append(
                        Finding(
                            path=path,
                            line_no=line_no,
                            reason=f"banned-comment-marker:{marker}",
                            snippet=snippet,
                        )
                    )

            if AI_DISCLOSURE_RE.search(text):
                findings.append(
                    Finding(
                        path=path,
                        line_no=line_no,
                        reason="ai-disclosure-comment",
                        snippet=snippet,
                    )
                )
    return findings


def main() -> int:
    added_lines = _git_added_lines()
    if not added_lines:
        return 0

    findings = _detect_findings(added_lines)
    for finding in findings:
        print(f"{finding.path}:{finding.line_no}: {finding.reason} -> {finding.snippet}")

    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
