"""Fail CI when newly added lines introduce AI-smell markers or merge conflicts."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass


BANNED_MARKERS = (
    "SENIOR-LEVEL",
    "ЗАЛІЗОБЕТОННО",
    "AI wrote this",
)

AI_DISCLOSURE_RE = re.compile(
    r"(as an ai|chatgpt|generated by ai|copilot|llm generated|written by ai)",
    re.IGNORECASE,
)

MERGE_CONFLICT_RE = re.compile(r"^(<<<<<<< .+|=======|>>>>>>> .+)$")

SOURCE_FILE_RE = re.compile(r"^\+\+\+ b/((?:src|tests|scripts)/.+\.pyi?)$")


@dataclass(frozen=True)
class Finding:
    path: str
    line_no: int
    reason: str
    snippet: str


def _parse_added_lines_from_unified_diff(diff_text: str) -> list[tuple[str, int, str]]:
    """Return (file, line_no, line_text) for added lines from unified diff text."""
    findings: list[tuple[str, int, str]] = []
    current_file: str | None = None
    current_new_line = 0
    for raw in diff_text.splitlines():
        file_match = SOURCE_FILE_RE.match(raw)
        if file_match:
            current_file = file_match.group(1)
            current_new_line = 0
            continue

        if raw.startswith("@@"):
            # Parse hunk header, e.g. @@ -10,0 +11,3 @@
            plus_part = raw.split("+", 1)[1].split(" ", 1)[0]
            current_new_line = int(plus_part.split(",")[0])
            continue

        if current_file is None:
            continue
        if raw.startswith("+++ ") or raw.startswith("--- "):
            continue
        if raw.startswith("+"):
            findings.append((current_file, current_new_line, raw[1:]))
            current_new_line += 1
        elif raw.startswith("-"):
            continue
        else:
            current_new_line += 1
    return findings


def _git_added_lines(*, base: str, head: str, merge_base: bool) -> list[tuple[str, int, str]]:
    """Return (file, line_no, line_text) for added lines in selected revision range."""
    revision_range = f"{base}...{head}" if merge_base else f"{base}..{head}"
    result = subprocess.run(
        ["git", "diff", "--unified=0", "--no-color", revision_range],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return []
    return _parse_added_lines_from_unified_diff(result.stdout)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fail when newly added lines contain AI-smell markers or merge conflict markers"
    )
    parser.add_argument("--base", default="HEAD~1", help="Base revision (default: HEAD~1)")
    parser.add_argument("--head", default="HEAD", help="Head revision (default: HEAD)")
    parser.add_argument(
        "--merge-base",
        action="store_true",
        help="Compare using merge-base (triple-dot diff, e.g. origin/main...HEAD)",
    )
    return parser.parse_args()


def _detect_findings(added_lines: list[tuple[str, int, str]]) -> list[Finding]:
    findings: list[Finding] = []
    for path, line_no, text in added_lines:
        snippet = text.strip()

        if MERGE_CONFLICT_RE.match(snippet):
            findings.append(
                Finding(path=path, line_no=line_no, reason="merge-conflict-marker", snippet=snippet)
            )

        if "#" in text:
            for marker in BANNED_MARKERS:
                if marker in text:
                    findings.append(
                        Finding(
                            path=path,
                            line_no=line_no,
                            reason=f"banned-comment-marker:{marker}",
                            snippet=snippet,
                        )
                    )

            if AI_DISCLOSURE_RE.search(text):
                findings.append(
                    Finding(
                        path=path,
                        line_no=line_no,
                        reason="ai-disclosure-comment",
                        snippet=snippet,
                    )
                )
    return findings


def main() -> int:
    args = _parse_args()
    added_lines = _git_added_lines(base=args.base, head=args.head, merge_base=args.merge_base)
    if not added_lines:
        return 0

    findings = _detect_findings(added_lines)
    for finding in findings:
        print(f"{finding.path}:{finding.line_no}: {finding.reason} -> {finding.snippet}")

    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
