from __future__ import annotations

from pathlib import Path
import re

ROOTS = (Path("src"), Path("tests"), Path("scripts"))
EXTENSIONS = {".py", ".pyi"}

FORBIDDEN_SNIPPETS = (
    "as an ai",
    "chatgpt",
    "generated by ai",
    "written by ai",
    "copilot",
    "llm generated",
)

MERGE_CONFLICT_RE = re.compile(r"^(<<<<<<< .+|=======|>>>>>>> .+)$")


def _iter_files() -> list[Path]:
    files: list[Path] = []
    for root in ROOTS:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.is_file() and path.suffix in EXTENSIONS:
                files.append(path)
    return files


def test_no_merge_conflict_or_ai_disclosure_markers() -> None:
    violations: list[str] = []

    for path in _iter_files():
        text = path.read_text(encoding="utf-8")
        for line_no, line in enumerate(text.splitlines(), start=1):
            stripped = line.strip()

            if MERGE_CONFLICT_RE.match(stripped):
                violations.append(f"{path}:{line_no} merge-conflict marker found: {stripped}")

            lower = stripped.lower()
            if not stripped.startswith("#"):
                continue

            for snippet in FORBIDDEN_SNIPPETS:
                if snippet in lower:
                    violations.append(f"{path}:{line_no} AI-disclosure marker found: {stripped}")
                    break

    assert not violations, "\n".join(violations)
